<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-InventoryWorker-51035387-4f1e-47a0-98c2-2f58d9aa2cdb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageReference Include="RabbitMQ.Client" Version="6.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\App\OrderService.Infrastructure\OrderService.Infrastructure.csproj" />
    <ProjectReference Include="..\..\App\OrderService.Application\OrderService.Application.csproj" />
  </ItemGroup>
</Project>
