<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-OrderWorker-2ecba921-5367-42dc-a879-c2da0cdc85ae</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.6" />
    <PackageReference Include="RabbitMQ.Client" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\App\OrderService.Application\OrderService.Application.csproj" />
    <ProjectReference Include="..\..\App\OrderService.Infrastructure\OrderService.Infrastructure.csproj" />
    <ProjectReference Include="..\..\App\OrderService.Domain\OrderService.Domain.csproj" />
  </ItemGroup>
</Project>
